### ISSUE TITLE
Can we use this creating session using python

### ISSUE THREAD

**Issue by mshazor11** [osen/vimux#1]

**Comment by osen** [comment]
The underlying system is using winpty. This is used by vim to create the :terminal function and I am really just hacking some shortcuts around that.

Is automating it via Python all you want? You could potentially use vim-remote to instruct vim to create a new session?

To re-write all vim's session related code in python (including winpty bindings) may be a fairly large task unfortunately.

Python is fairly large so perhaps you would consider installing msys2, cygwin, etc on your Windows machine instead and using the real tmux?
