### ISSUE TITLE
open source?

### ISSUE THREAD

**Issue by christopherfujino** [osen/vimux#3]
Would it be possible to share the source?

**Comment by osen** [comment]
There is not really any source to share. vimux is in essence just a batch file and a config file for Vim.
It bundles a binary copy of Vim but you could likely compile your own version and substitute that if you needed to.

**Comment by christopherfujino** [comment]
ahh, i see, so this project is just key bindings for vim to give a tmux-like window/tab workflow?

**Comment by osen** [comment]
Exactly. It is surprisingly popular for just that; suggesting that some sort of proper terminal multiplexer for conhost/powershell could be quite useful to people.

**Comment by christopherfujino** [comment]
Thanks
